In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, auc, confusion_matrix, precision_score, recall_score, roc_curve,classification_report
import matplotlib.pyplot as plt
import seaborn as sns


In [23]:
#!wget https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

In [24]:
data = pd.read_csv("iris.data")

In [25]:
data.head()


5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [26]:
data.columns=['sepal length','sepal width','petal length','petal width','class']

In [27]:
data.head(3)

sepal length  sepal width  petal length  petal width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa

In [28]:
print(data.isnull().sum())
print(data.shape)

sepal length    0
sepal width     0
petal length    0
petal width     0
class           0
dtype: int64
(149, 5)


In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
sepal length    149 non-null float64
sepal width     149 non-null float64
petal length    149 non-null float64
petal width     149 non-null float64
class           149 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [30]:
x = data.iloc[:,0:4]
y = data['class']

In [31]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y1 = labelencoder.fit_transform(y)

#y = pd.get_dummies(y1).values

In [32]:
y = pd.get_dummies(y1).values

In [33]:
#y

In [34]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=70)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((119, 4), (30, 4), (119, 3), (30, 3))

In [35]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation

In [36]:
model = Sequential()
model.add(Dense(4,input_shape=(4,), activation='relu'))
model.add(Dense(4,input_shape=(4,), activation='relu'))

In [37]:
model.add(Dense(3, activation='softmax'))

In [38]:
model.compile(loss='categorical_crossentropy',
              optimizer='Adam',
              metrics=['accuracy'])

In [39]:
model.fit(x_train, y_train, batch_size=10, nb_epoch=100)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  if __name__ == '__main__':


Epoch 1/100
119/119 [==============================] - 0s 3ms/step - loss: 1.0238 - accuracy: 0.6807
Epoch 2/100
119/119 [==============================] - 0s 235us/step - loss: 1.0087 - accuracy: 0.6807
Epoch 3/100
119/119 [==============================] - 0s 222us/step - loss: 0.9962 - accuracy: 0.6807
Epoch 4/100
119/119 [==============================] - 0s 276us/step - loss: 0.9715 - accuracy: 0.6807
Epoch 5/100
119/119 [==============================] - 0s 201us/step - loss: 0.9150 - accuracy: 0.6807
Epoch 6/100
119/119 [==============================] - 0s 199us/step - loss: 0.8727 - accuracy: 0.6807
Epoch 7/100
119/119 [==============================] - 0s 191us/step - loss: 0.8481 - accuracy: 0.6807
Epoch 8/100
119/119 [==============================] - 0s 184us/step - loss: 0.8286 - accuracy: 0.6807
Epoch 9/100
119/119 [==============================] - 0s 211us/step - loss: 0.8054 - accuracy: 0.6807
Epoch 10/100
119/119 [==============================] - 0s 215us/step - los

119/119 [==============================] - 0s 278us/step - loss: 0.1379 - accuracy: 0.9832
Epoch 80/100
119/119 [==============================] - 0s 233us/step - loss: 0.1315 - accuracy: 0.9832
Epoch 81/100
119/119 [==============================] - 0s 430us/step - loss: 0.1299 - accuracy: 0.9916
Epoch 82/100
119/119 [==============================] - 0s 250us/step - loss: 0.1280 - accuracy: 0.9916
Epoch 83/100
119/119 [==============================] - 0s 267us/step - loss: 0.1256 - accuracy: 0.9832
Epoch 84/100
119/119 [==============================] - 0s 315us/step - loss: 0.1219 - accuracy: 0.9916
Epoch 85/100
119/119 [==============================] - 0s 223us/step - loss: 0.1203 - accuracy: 0.9916
Epoch 86/100
119/119 [==============================] - 0s 340us/step - loss: 0.1173 - accuracy: 0.9916
Epoch 87/100
119/119 [==============================] - 0s 244us/step - loss: 0.1155 - accuracy: 0.9916
Epoch 88/100
119/119 [==============================] - 0s 264us/step - loss:

In [40]:
y_pred = model.predict(x_test)
y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

In [41]:
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.83      0.91        12
           2       0.82      1.00      0.90         9

   micro avg       0.93      0.93      0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.95      0.93      0.93        30

[[ 9  0  0]
 [ 0 10  2]
 [ 0  0  9]]


In [42]:
(28)/30

0.9333333333333333